sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t efeberkeevci/docker_kubernetes_tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true efeberkeevci/docker_kubernetes_tutorial npm run test

